#!/usr/bin/env python3
"""Detect likely AI-generated images and choose print defaults.

The client hands over a picture. This module decides whether it looks like
generator artwork (ChatGPT, Midjourney, Flux and similar sizes or tags) and
which press defaults to pre-select. Nothing here blocks the job, and every
choice can be overridden.

Illustrator .ai / .eps intake is intentionally not handled here.
"""

from __future__ import annotations

import os
from typing import Any, Callable, Optional

import cv2
import numpy as np
from PIL import Image

from colour_border import bgr_to_cmyk, cmyk_to_bgr, sample_edge_cmyk

# Common generator exports. Both orientations are listed. Match within 2px.
GENERATOR_SIZES = frozenset({
    (256, 256),
    (512, 512),
    (512, 768),
    (768, 512),
    (768, 768),
    (640, 1536),
    (768, 1344),
    (816, 1456),
    (832, 1216),
    (896, 1152),
    (928, 1232),
    (1024, 1024),
    (1024, 1365),
    (1024, 1536),
    (1024, 1792),
    (1152, 896),
    (1152, 2048),
    (1216, 832),
    (1232, 928),
    (1344, 768),
    (1365, 1024),
    (1456, 816),
    (1536, 640),
    (1536, 1024),
    (1792, 1024),
    (2048, 1152),
    (2048, 2048),
})

AI_META_PHRASES = (
    "midjourney",
    "openai",
    "dall-e",
    "dalle-3",
    "dalle",
    "chatgpt",
    "stable diffusion",
    "stablediffusion",
    "comfyui",
    "novelai",
    "ideogram",
    "adobe firefly",
    "firefly",
    "leonardo.ai",
    "dreamstudio",
    "flux.1",
    "black forest labs",
    "generated by ai",
    "ai-generated",
    "ai generated",
)

C2PA_MARKERS = ("c2pa", "jumbf", "content credentials", "cai:claim")

FLAT_EDGE_STD = 14.0
RATIO_TOLERANCE = 0.015
SAFE_ZONE_MM = 5.0
MAX_LONG_EDGE = 4000
TARGET_DPI = 300

SpellFn = Callable[[str], dict]
ExpandFn = Callable[[str], dict]
_SPELL: Optional[SpellFn] = None
_EXPAND: Optional[ExpandFn] = None


def set_spell_checker(fn: Optional[SpellFn]) -> None:
    """Test hook. fn(path) -> spell_check-shaped dict. None uses Gemini."""
    global _SPELL
    _SPELL = fn


def set_expand_fn(fn: Optional[ExpandFn]) -> None:
    """Test hook. fn(path) -> expand_background-shaped dict."""
    global _EXPAND
    _EXPAND = fn


def size_match(width: int, height: int) -> Optional[tuple[int, int]]:
    for sw, sh in GENERATOR_SIZES:
        if abs(int(width) - sw) <= 2 and abs(int(height) - sh) <= 2:
            return sw, sh
    return None


def _read_meta_blob(path: str, pil_info: dict) -> str:
    parts: list[str] = []
    for value in (pil_info or {}).values():
        if isinstance(value, str):
            parts.append(value)
        elif isinstance(value, bytes):
            parts.append(value.decode("latin-1", errors="ignore"))
    try:
        size = os.path.getsize(path)
        with open(path, "rb") as handle:
            parts.append(handle.read(400_000).decode("latin-1", errors="ignore"))
            if size > 500_000:
                handle.seek(max(0, size - 80_000))
                parts.append(handle.read(80_000).decode("latin-1", errors="ignore"))
    except OSError:
        pass
    return " ".join(parts).lower()


def _dpi_from_pil(im: Image.Image) -> Optional[tuple[float, float]]:
    dpi = im.info.get("dpi")
    if isinstance(dpi, (tuple, list)) and len(dpi) >= 2 and float(dpi[0] or 0) > 0:
        return float(dpi[0]), float(dpi[1] or dpi[0])
    density = im.info.get("jfif_density")
    unit = im.info.get("jfif_unit", 0)
    if isinstance(density, (tuple, list)) and len(density) >= 2 and density[0]:
        if unit == 1:
            return float(density[0]), float(density[1] or density[0])
        if unit == 2:
            return float(density[0]) * 2.54, float(density[1] or density[0]) * 2.54
    return None


def dpi_is_weak(dpi: Optional[tuple[float, float]]) -> bool:
    if not dpi:
        return True
    return dpi[0] <= 96.5 and dpi[1] <= 96.5


def edge_std(bgr: np.ndarray) -> float:
    """Standard deviation of the outer 1-pixel ring."""
    if bgr is None or bgr.size == 0:
        return 0.0
    plane = bgr
    if plane.ndim == 2:
        plane = cv2.cvtColor(plane, cv2.COLOR_GRAY2BGR)
    if plane.shape[2] == 4:
        plane = plane[:, :, :3]
    height, width = plane.shape[:2]
    strips = [plane[0, :, :], plane[-1, :, :]]
    if height > 2:
        strips.append(plane[1:-1, 0, :])
        strips.append(plane[1:-1, -1, :])
    edge = np.concatenate([strip.reshape(-1, 3) for strip in strips], axis=0).astype(np.float32)
    # Variation across pixels. Mixing the colour channels would look "noisy" on a flat red. 
    return float(edge.std(axis=0).mean())


def has_separate_bleed_margin(bgr: np.ndarray, dpi: Optional[float]) -> bool:
    """True when a uniform outer margin differs from the picture inside it.

    This only classifies an existing margin. Edge colour for a new border
    still uses the 1-pixel sampler.
    """
    if bgr is None or dpi is None or dpi < 150:
        return False
    height, width = bgr.shape[:2]
    margin = int(round(float(dpi) * 3.0 / 25.4))
    if margin < 4 or height <= margin * 3 or width <= margin * 3:
        return False
    if edge_std(bgr) > FLAT_EDGE_STD:
        return False
    inset = bgr[margin:-margin, margin:-margin]
    if inset.size == 0:
        return False
    outer = sample_edge_cmyk(bgr)
    inner_mean = inset.reshape(-1, inset.shape[-1])[:, :3].mean(axis=0)
    inner = bgr_to_cmyk(float(inner_mean[0]), float(inner_mean[1]), float(inner_mean[2]))
    distance = sum(abs(a - b) for a, b in zip(outer, inner))
    return distance > 25.0


def detect_ai_artwork(path: str, bgr: Optional[np.ndarray] = None) -> dict:
    """Return detection signals. A normal photo at an ordinary size is not flagged."""
    reasons: list[str] = []
    with Image.open(path) as im:
        width, height = im.size
        mode = im.mode
        dpi = _dpi_from_pil(im)
        blob = _read_meta_blob(path, dict(im.info or {}))
    if bgr is None:
        bgr = cv2.imread(path, cv2.IMREAD_COLOR)

    matched = size_match(width, height)
    meta_hits = [phrase for phrase in AI_META_PHRASES if phrase in blob]
    c2pa = any(marker in blob for marker in C2PA_MARKERS)
    rgb = mode in ("RGB", "RGBA", "P")
    weak = dpi_is_weak(dpi)
    dpi_value = float(dpi[0]) if dpi else 0.0
    separate_bleed = has_separate_bleed_margin(bgr, dpi_value if dpi else None)
    no_bleed = not separate_bleed

    if matched:
        reasons.append(f"{width}×{height} pixels matches a common AI image size")
    if meta_hits:
        reasons.append(f"file metadata mentions {meta_hits[0]}")
    elif c2pa and matched:
        reasons.append("file has content-credentials metadata on an AI image size")
    if rgb and weak:
        reasons.append("RGB with no print DPI, or 72/96 DPI")
    if no_bleed:
        reasons.append("no built-in bleed margin")

    detected = bool(meta_hits) or bool(matched and (weak or c2pa or (rgb and no_bleed)))
    if not detected:
        reasons = []
    return {
        "detected": detected,
        "reasons": reasons,
        "src_w": int(width),
        "src_h": int(height),
        "mode": mode,
        "dpi": round(dpi_value, 2),
        "rgb": rgb,
        "dpi_weak": weak,
        "no_bleed": no_bleed,
        "metadata": bool(meta_hits or (c2pa and matched)),
    }


def ratios_differ(src_w: int, src_h: int, trim_w_mm: float, trim_h_mm: float) -> bool:
    if min(src_w, src_h, trim_w_mm, trim_h_mm) <= 0:
        return False
    src = float(src_w) / float(src_h)
    target = float(trim_w_mm) / float(trim_h_mm)
    return abs(src - target) / target > RATIO_TOLERANCE


def cover_crop_box(src_w: int, src_h: int, trim_w_mm: float, trim_h_mm: float, offset: float = 0.5) -> dict:
    """Cover crop in source pixels. offset 0.5 keeps the middle. Safe zone is 5mm."""
    offset = max(0.0, min(1.0, float(offset)))
    target = float(trim_w_mm) / float(trim_h_mm)
    src = float(src_w) / float(src_h)
    if not ratios_differ(src_w, src_h, trim_w_mm, trim_h_mm):
        box = {"x": 0, "y": 0, "w": int(src_w), "h": int(src_h), "axis": "none"}
    elif src > target:
        crop_w = max(1, int(round(src_h * target)))
        crop_w = min(crop_w, src_w)
        slack = src_w - crop_w
        box = {
            "x": int(round(slack * offset)),
            "y": 0,
            "w": crop_w,
            "h": int(src_h),
            "axis": "x",
        }
    else:
        crop_h = max(1, int(round(src_w / target)))
        crop_h = min(crop_h, src_h)
        slack = src_h - crop_h
        box = {
            "x": 0,
            "y": int(round(slack * offset)),
            "w": int(src_w),
            "h": crop_h,
            "axis": "y",
        }
    box["safe_mm"] = SAFE_ZONE_MM
    box["safe_x"] = SAFE_ZONE_MM / float(trim_w_mm) if trim_w_mm else 0
    box["safe_y"] = SAFE_ZONE_MM / float(trim_h_mm) if trim_h_mm else 0
    return box


def _cap_long_edge(img: np.ndarray) -> np.ndarray:
    height, width = img.shape[:2]
    long_edge = max(height, width)
    if long_edge <= MAX_LONG_EDGE:
        return img
    scale = MAX_LONG_EDGE / float(long_edge)
    return cv2.resize(
        img,
        (max(1, int(round(width * scale))), max(1, int(round(height * scale)))),
        interpolation=cv2.INTER_AREA,
    )


def mirror_extend_to_ratio(img: np.ndarray, target_ratio: float) -> np.ndarray:
    """Keep the whole picture and mirror the edges until the aspect matches.

    Reflect-101 mirrors from the outer pixel inward, so the new margin is an
    extension of the edge rather than a stretched copy of the middle.
    """
    height, width = img.shape[:2]
    if height < 1 or width < 1 or target_ratio <= 0:
        return img
    current = width / float(height)
    if abs(current - target_ratio) / target_ratio <= RATIO_TOLERANCE:
        return img
    if current > target_ratio:
        new_h = int(round(width / target_ratio))
        pad = max(0, new_h - height)
        top = pad // 2
        bottom = pad - top
        out = cv2.copyMakeBorder(img, top, bottom, 0, 0, cv2.BORDER_REFLECT_101)
    else:
        new_w = int(round(height * target_ratio))
        pad = max(0, new_w - width)
        left = pad // 2
        right = pad - left
        out = cv2.copyMakeBorder(img, 0, 0, left, right, cv2.BORDER_REFLECT_101)
    return _cap_long_edge(out)


def colour_border_to_ratio(img: np.ndarray, target_ratio: float, bgr_colour: tuple[int, int, int]) -> np.ndarray:
    """Keep the whole picture and fill the gaps with a flat edge colour."""
    height, width = img.shape[:2]
    if height < 1 or width < 1 or target_ratio <= 0:
        return img
    current = width / float(height)
    if abs(current - target_ratio) / target_ratio <= RATIO_TOLERANCE:
        return img
    if current > target_ratio:
        new_h = int(round(width / target_ratio))
        canvas_w, canvas_h = width, max(height, new_h)
    else:
        new_w = int(round(height * target_ratio))
        canvas_w, canvas_h = max(width, new_w), height
    canvas = np.empty((canvas_h, canvas_w, 3), dtype=np.uint8)
    canvas[:, :] = bgr_colour
    y = max(0, (canvas_h - height) // 2)
    x = max(0, (canvas_w - width) // 2)
    canvas[y:y + height, x:x + width] = img[:, :, :3] if img.ndim == 3 else img
    return _cap_long_edge(canvas)


def crop_to_ratio(img: np.ndarray, trim_w_mm: float, trim_h_mm: float, offset: float) -> np.ndarray:
    height, width = img.shape[:2]
    box = cover_crop_box(width, height, trim_w_mm, trim_h_mm, offset)
    x, y, cw, ch = int(box["x"]), int(box["y"]), int(box["w"]), int(box["h"])
    x = max(0, min(x, width - 1))
    y = max(0, min(y, height - 1))
    cw = max(1, min(cw, width - x))
    ch = max(1, min(ch, height - y))
    return img[y:y + ch, x:x + cw]


def apply_artwork_fit(
    img: np.ndarray,
    trim_w_mm: float,
    trim_h_mm: float,
    fit: str,
    offset: float = 0.5,
    border_cmyk: tuple[float, float, float, float] = (0, 0, 0, 0),
    source_path: str = "",
    expand_fn: Optional[ExpandFn] = None,
) -> tuple[np.ndarray, dict]:
    """Fit the raster to the print aspect before cover-scale. Failures keep the original."""
    info = {"fit": fit, "expand": "skipped"}
    if img is None or img.size == 0 or fit not in ("crop", "extend", "border"):
        return img, info
    working = img
    if fit == "extend" and source_path:
        fn = expand_fn if expand_fn is not None else _EXPAND
        if fn is not None:
            try:
                result = fn(source_path) or {}
            except Exception as exc:
                result = {"stub": True, "message": str(exc)[:160]}
            enhanced = str(result.get("enhanced_path") or "")
            used_ai = bool(result.get("success") and not result.get("stub") and enhanced and os.path.exists(enhanced))
            if used_ai and os.path.abspath(enhanced) != os.path.abspath(source_path):
                loaded = cv2.imread(enhanced, cv2.IMREAD_COLOR)
                if loaded is not None and loaded.size:
                    working = loaded
                    info["expand"] = "ai"
                else:
                    info["expand"] = "local"
            else:
                info["expand"] = "local"
        else:
            info["expand"] = "local"
    try:
        if fit == "crop":
            working = crop_to_ratio(working, trim_w_mm, trim_h_mm, offset)
        elif fit == "extend":
            target = float(trim_w_mm) / float(trim_h_mm)
            working = mirror_extend_to_ratio(working, target)
        elif fit == "border":
            target = float(trim_w_mm) / float(trim_h_mm)
            colour = cmyk_to_bgr(border_cmyk)
            working = colour_border_to_ratio(working, target, colour)
    except Exception:
        return img, {"fit": "none", "expand": "skipped"}
    return working, info


def bright_rgb_fraction(bgr: np.ndarray) -> float:
    """Share of pixels that are vivid on screen and will dull in CMYK."""
    if bgr is None or bgr.size == 0:
        return 0.0
    small = bgr
    long_edge = max(bgr.shape[:2])
    if long_edge > 256:
        scale = 256.0 / float(long_edge)
        small = cv2.resize(bgr, (max(1, int(round(bgr.shape[1] * scale))), max(1, int(round(bgr.shape[0] * scale)))), interpolation=cv2.INTER_AREA)
    hsv = cv2.cvtColor(small[:, :, :3], cv2.COLOR_BGR2HSV)
    sat = hsv[:, :, 1].astype(np.float32)
    val = hsv[:, :, 2].astype(np.float32)
    hot = (sat > 180) & (val > 180)
    return float(hot.mean())


def make_soft_proof(bgr: np.ndarray, max_edge: int = 640) -> tuple[np.ndarray, np.ndarray]:
    """Approximate screen vs litho preview. The press file still uses FOGRA39."""
    height, width = bgr.shape[:2]
    long_edge = max(height, width, 1)
    if long_edge > max_edge:
        scale = max_edge / float(long_edge)
        screen = cv2.resize(
            bgr[:, :, :3],
            (max(1, int(round(width * scale))), max(1, int(round(height * scale)))),
            interpolation=cv2.INTER_AREA,
        )
    else:
        screen = bgr[:, :, :3].copy()
    hsv = cv2.cvtColor(screen, cv2.COLOR_BGR2HSV).astype(np.float32)
    hot = hsv[:, :, 1] > 170
    hsv[:, :, 1] = np.where(hot, hsv[:, :, 1] * 0.55, hsv[:, :, 1])
    proof = cv2.cvtColor(np.clip(hsv, 0, 255).astype(np.uint8), cv2.COLOR_HSV2BGR)
    return screen, proof


def save_png_300(bgr: np.ndarray, path: str) -> None:
    rgb = cv2.cvtColor(bgr[:, :, :3], cv2.COLOR_BGR2RGB)
    Image.fromarray(rgb).save(path, format="PNG", dpi=(300, 300))


def _default_spell(path: str) -> dict:
    from ai_enhancements import apply_spell_check
    return apply_spell_check(path)


def _default_expand(path: str) -> dict:
    from ai_enhancements import apply_expand_background
    return apply_expand_background(path)


def check_text(path: str, spell_fn: Optional[SpellFn] = None) -> dict:
    """Flag suspicious wording. Never raises and never blocks the job."""
    fn = spell_fn if spell_fn is not None else (_SPELL or _default_spell)
    try:
        result = fn(path) or {}
    except Exception as exc:
        return {
            "text_status": "unavailable",
            "text_warnings": [],
            "text_message": "Text check could not run, so give any wording a quick look. The job was not stopped.",
            "blocked": False,
            "detail": str(exc)[:160],
        }
    if result.get("stub") or result.get("success") is False:
        return {
            "text_status": "unavailable",
            "text_warnings": [],
            "text_message": "Text check could not run, so give any wording a quick look. The job was not stopped.",
            "blocked": False,
        }
    raw = result.get("errors_found") or result.get("errors") or []
    warnings = []
    if isinstance(raw, list):
        for item in raw:
            if not isinstance(item, dict):
                continue
            word = str(item.get("word") or "").strip()
            suggestion = str(item.get("suggestion") or "").strip()
            if word:
                warnings.append({"word": word[:80], "suggestion": suggestion[:80]})
    if warnings:
        shown = "; ".join(
            f"'{item['word']}' → '{item['suggestion']}'" if item["suggestion"] else f"'{item['word']}'"
            for item in warnings[:6]
        )
        message = f"Possible text problem: {shown}. The job was not stopped."
        status = "warning"
    else:
        message = "Text check found nothing suspicious."
        status = "clear"
    return {
        "text_status": status,
        "text_warnings": warnings,
        "text_message": message,
        "blocked": False,
    }


def _effective_dpi(px_w: int, px_h: int, trim_w: float, trim_h: float) -> int:
    from ai_upscale import effective_print_dpi
    return int(effective_print_dpi(px_w, px_h, trim_w, trim_h, 5.0))


def _bleed_choice(bgr: np.ndarray) -> tuple[str, dict]:
    cmyk = sample_edge_cmyk(bgr)
    edge = {"c": cmyk[0], "m": cmyk[1], "y": cmyk[2], "k": cmyk[3]}
    if edge_std(bgr) <= FLAT_EDGE_STD:
        return "colourBorder", edge
    return "mirror", edge


def build_note(applied: list[str], text_message: str, bright_message: str) -> str:
    body = "; ".join(applied)
    parts = [f"AI-generated artwork detected. Auto-applied: {body}."]
    if text_message:
        parts.append(text_message)
    if bright_message:
        parts.append(bright_message)
    parts.append("You can change any of these.")
    return " ".join(parts)


def plan_artwork(path: str, trim_w_mm: float, trim_h_mm: float, options: Optional[dict] = None) -> dict:
    """Full recommendation for one image. Safe to call when the file is not AI."""
    options = options or {}
    bgr = cv2.imread(path, cv2.IMREAD_COLOR)
    if bgr is None:
        return {"success": True, "detected": False, "blocked": False, "message": "This file is not a picture we can check."}

    found = detect_ai_artwork(path, bgr)
    if not found["detected"]:
        return {"success": True, "detected": False, "blocked": False, "src_w": found["src_w"], "src_h": found["src_h"]}

    trim_w = float(trim_w_mm or 148)
    trim_h = float(trim_h_mm or 210)
    mismatch = ratios_differ(found["src_w"], found["src_h"], trim_w, trim_h)
    bleed, edge = _bleed_choice(bgr)
    dpi_now = _effective_dpi(found["src_w"], found["src_h"], trim_w, trim_h)
    enhance = dpi_now < TARGET_DPI
    fit = "crop" if mismatch else "none"
    offset = 0.5

    if mismatch and options.get("fit") in ("crop", "extend", "border"):
        fit = options["fit"]
    if options.get("offset") is not None:
        try:
            offset = max(0.0, min(1.0, float(options["offset"])))
        except (TypeError, ValueError):
            offset = 0.5
    if options.get("bleed") in ("mirror", "colourBorder", "replicate", "stretch", "bgExtract"):
        bleed = options["bleed"]
    if options.get("use_given_enhance"):
        enhance = bool(options.get("enhance"))

    reuse = options.get("reuse_text")
    if isinstance(reuse, dict) and reuse.get("text_message"):
        text = {
            "text_status": reuse.get("text_status") or "unavailable",
            "text_warnings": reuse.get("text_warnings") or [],
            "text_message": reuse.get("text_message") or "",
            "blocked": False,
        }
    else:
        text = check_text(path)

    hot = bright_rgb_fraction(bgr) >= 0.008
    bright_message = ""
    if hot:
        bright_message = (
            "Some bright screen colours will look duller in print. "
            "The preview is approximate — the press file still uses the FOGRA39 CMYK conversion."
        )

    screen_path = str(options.get("screen_preview") or "")
    print_path = str(options.get("print_preview") or "")
    source_path = str(options.get("source_preview") or "")
    if screen_path and print_path:
        try:
            screen, proof = make_soft_proof(bgr)
            save_png_300(screen, screen_path)
            save_png_300(proof, print_path)
        except Exception:
            pass
    if source_path:
        try:
            long_edge = max(bgr.shape[:2])
            shown = bgr
            if long_edge > 900:
                scale = 900.0 / float(long_edge)
                shown = cv2.resize(
                    bgr,
                    (max(1, int(round(bgr.shape[1] * scale))), max(1, int(round(bgr.shape[0] * scale)))),
                    interpolation=cv2.INTER_AREA,
                )
            save_png_300(shown, source_path)
        except Exception:
            pass

    applied: list[str] = []
    if mismatch and fit == "crop":
        applied.append("crop to fit, with the safe zone shown")
    elif mismatch and fit == "extend":
        if expand_is_configured() or _EXPAND is not None:
            applied.append("extend the background to the page shape, using AI expand when it returns a larger picture")
        else:
            applied.append("extend the background to the page shape on this computer")
    elif mismatch and fit == "border":
        applied.append("colour border matched to the edge colour to fill the page shape")
    elif not mismatch:
        applied.append("page shape already matches the print size")

    if bleed == "colourBorder":
        applied.append("Colour Border bleed matched to the edge colour")
    elif bleed == "mirror":
        applied.append("Mirror bleed, because the edges look photographic")
    else:
        applied.append(f"{bleed} bleed")

    if enhance:
        applied.append(f"AI Enhance on, because the picture is about {dpi_now} DPI at this print size (under 300)")
    else:
        applied.append(f"AI Enhance left off, because the picture is about {dpi_now} DPI at this print size")
    applied.append("CMYK conversion for litho print")

    note = build_note(applied, text["text_message"], bright_message)
    crop = cover_crop_box(found["src_w"], found["src_h"], trim_w, trim_h, offset)
    return {
        "success": True,
        "detected": True,
        "blocked": False,
        "reasons": found["reasons"],
        "src_w": found["src_w"],
        "src_h": found["src_h"],
        "dpi": found["dpi"],
        "mismatch": mismatch,
        "fit": fit if mismatch else "none",
        "offset": offset,
        "crop": crop,
        "bleed": bleed,
        "edge": edge,
        "edge_flat": edge_std(bgr) <= FLAT_EDGE_STD,
        "enhance": enhance,
        "effective_dpi": dpi_now,
        "bright": hot,
        "bright_message": bright_message,
        "text_status": text["text_status"],
        "text_warnings": text["text_warnings"],
        "text_message": text["text_message"],
        "applied": applied,
        "note": note,
    }


def configured_expand(path: str) -> dict:
    """Call expand_background only when a token or a test hook is present."""
    if _EXPAND is not None:
        return _EXPAND(path)
    if not expand_is_configured():
        return {
            "success": True,
            "stub": True,
            "enhanced_path": path,
            "message": "Background expansion requires API configuration. Your original artwork is preserved.",
        }
    return _default_expand(path)


def expand_is_configured() -> bool:
    try:
        from ai_enhancements import _get_replicate_token
        return bool(_get_replicate_token())
    except Exception:
        return False
