// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-layouts/CommandCenter.tsx": () => import("../components/mockups/dashboard-layouts/CommandCenter.tsx"),
  "./components/mockups/dashboard-layouts/ProgressiveFocus.tsx": () => import("../components/mockups/dashboard-layouts/ProgressiveFocus.tsx"),
  "./components/mockups/dashboard-layouts/SplitScreen.tsx": () => import("../components/mockups/dashboard-layouts/SplitScreen.tsx")
};
